# Generated by Django 5.1.4 on 2024-12-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestPrompt',
            new_name='Prompt',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='test',
            new_name='prompt',
        ),
    ]
